# Generate a .h file with a static array declaration of the EEPROM image to include in the arduino program memory 
# The ATMEGA2560 only has 8kB SRAM, so any large data needs to go into the 256kB flash.
# To do so, the data must be defined in const arrays with the "PROGMEM" attribute
# Because the compiler limits individual progmem declarations to 16k, we define each 512B page as its own array
# Program memory may only be read at runtime through the "pgm_read_*" macros

PAGE_SIZE = 64
NUM_PAGES = 512
EEPROM_IMAGE_SIZE = 32768

eepromImage = [0xEA] * 32768

eepromImage[0x7FFC] = 0x00; # $PC = 0x8000
eepromImage[0x7FFD] = 0x80;
eepromImage[0x0000] = 0xA2; # LDX #0xAA
eepromImage[0x0001] = 0xAA; 
eepromImage[0x0002] = 0x8E; # STX 0x2000
eepromImage[0x0003] = 0x00;
eepromImage[0x0004] = 0x20;

eepromImage[0x0A0A] = 0xEE;
eepromImage[0x0B0B] = 0xEE;
eepromImage[0x0C0C] = 0xEE;
eepromImage[0x0D0D] = 0xEE;
eepromImage[0x0E0E] = 0xEE;

"""
for i in range(0, 64):
    eepromImage[i] = 64-i
"""


with open("EepromImage.h", "w") as f:
    f.write("//This File Auto-Generated by ImageGenerator.py\n\n");
    f.write("#include <inttypes.h>\n\n")
    f.write("#define PAGE_SIZE 64\n")
    f.write("#define NUM_PAGES 512\n")
    f.write("#define EEPROM_IMAGE_SIZE (32768)\n")
    
    # Macro to get reference to a page array by its page number
    f.write("#define EEPROM_PAGE(x) (_EEPROM_PAGES[x])\n\n")
    
    # Declare one array for every page in eepromImage
    for index in range(0, len(eepromImage)):
        pageNum = index // PAGE_SIZE
        if index % PAGE_SIZE == 0:
            f.write(f"const uint8_t _EEPROM_IMAGE_PAGE{pageNum}[PAGE_SIZE] PROGMEM = {{")
            f.write(f"0x{eepromImage[index]:X}, ")
        elif index % PAGE_SIZE == PAGE_SIZE - 1:
            f.write(f"0x{eepromImage[index]:X}}};\n")
        else:
            f.write(f"0x{eepromImage[index]:X}, ")
    f.write("\n")
    
    # Declare an array of pointers to each page
    # This one has to go in SRAM not flash, because it's pointers aren't literal constants
    f.write(f"const uint8_t* _EEPROM_PAGES[{NUM_PAGES}] = {{")
    for p in range(0, NUM_PAGES):
        f.write(f"_EEPROM_IMAGE_PAGE{p}")
        if p < NUM_PAGES - 1:
            f.write(", ")
        if p % 10 == 9:
            f.write("\n")
    f.write("};\n");
    
   
    
